[package]
name = "findtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["json", "cookies"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
regex = "1.5.4"
actix-web = "4"
futures = "0.3.28"
actix-files = "0.6.2"
chrono = "0.4.31"
log = "0.4"
env_logger = "0.10"
rand = "0.8.5"
openssl = { version = "0.10.60", features = ["vendored"] }
litemap = "=0.7.4" # 0.7.5
zerofrom = "=0.1.5" # 0.1.6

